<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "media_frontend"
 *
 * Auto generated by Extension Builder 2013-09-22
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Frontend Media',
	'description' => 'Frontend Media allows logged in visitors of the website to manage files through the frontend. They can be added, removed, altered and shared with other users. A plugin allows to show individual files or file collections.',
	'category' => 'plugin',
	'author' => 'Dirk Wenzel',
	'author_email' => 'wenzel@webfox01.de',
	'author_company' => 'Agentur Webfox',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'extbase' => '6.0',
			'fluid' => '6.0',
			'typo3' => '6.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>